#!/bin/sh

set -e

cd vendor/apache_1.3.42

./configure --prefix=`pwd`/../apachebin --activate-module=src/modules/cntr/libcntr.a

make

make install

make distclean

../apachebin/bin/httpd -l | grep cntr
